version: '3.8'

services:

  db:
    image: postgres:13.0-alpine
    volumes:
      - micro_auth_postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    restart: always
    ports:
      - "5430:5432"
    networks:
      - micro_auth_network

  micro_service:
    image:
      micro_service
    networks:
      - micro_auth_network

networks:
  micro_auth_network:
    driver: bridge

volumes:
  micro_auth_postgres_data:
    external: true

